import { Product } from '../types/types';

export const fetchProducts = async (): Promise<Product[]> => {
    // Simulate API delay
    await new Promise((res) => setTimeout(res, 500));

    return [
        {
            id: 1,
            name: 'Wireless Mouse',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Ergonomic wireless mouse with adjustable DPI.',
            price: 25.99,
            stock: 120,
            categoryId: 2,
            supplierId: 1,
        },
        {
            id: 2,
            name: 'Mechanical Keyboard',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'RGB mechanical keyboard with blue switches.',
            price: 79.99,
            stock: 75,
            categoryId: 2,
            supplierId: 2,
        },
        {
            id: 3,
            name: '4K Monitor',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: '27-inch 4K UHD monitor with HDR support.',
            price: 299.99,
            stock: 30,
            categoryId: 3,
            supplierId: 3,
        },
        {
            id: 4,
            name: 'USB-C Hub',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: '7-in-1 USB-C hub with HDMI and SD card reader.',
            price: 45.0,
            stock: 150,
            categoryId: 4,
            supplierId: 1,
        },
        {
            id: 5,
            name: 'Laptop Stand',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Adjustable aluminum laptop stand.',
            price: 32.5,
            stock: 60,
            categoryId: 5,
            supplierId: 2,
        },
        {
            id: 6,
            name: 'Noise Cancelling Headphones',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Over-ear wireless headphones with ANC.',
            price: 120.0,
            stock: 45,
            categoryId: 6,
            supplierId: 4,
        },
        {
            id: 7,
            name: 'Portable SSD 1TB',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'High-speed external solid-state drive.',
            price: 139.99,
            stock: 85,
            categoryId: 7,
            supplierId: 5,
        },
        {
            id: 8,
            name: 'Webcam 1080p',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Full HD webcam with built-in microphone.',
            price: 55.99,
            stock: 95,
            categoryId: 8,
            supplierId: 2,
        },
        {
            id: 9,
            name: 'Smartphone Tripod',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Flexible tripod stand for phones.',
            price: 18.99,
            stock: 110,
            categoryId: 5,
            supplierId: 6,
        },
        {
            id: 10,
            name: 'Gaming Chair',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Ergonomic gaming chair with lumbar support.',
            price: 199.0,
            stock: 20,
            categoryId: 9,
            supplierId: 4,
        },
        {
            id: 11,
            name: 'Bluetooth Speaker',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Portable Bluetooth speaker with bass boost.',
            price: 49.99,
            stock: 130,
            categoryId: 6,
            supplierId: 7,
        },
        {
            id: 12,
            name: 'Wireless Charger',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Fast wireless charging pad.',
            price: 27.5,
            stock: 90,
            categoryId: 4,
            supplierId: 5,
        },
        {
            id: 13,
            name: 'Drawing Tablet',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Digital drawing tablet for artists.',
            price: 99.99,
            stock: 40,
            categoryId: 10,
            supplierId: 3,
        },
        {
            id: 14,
            name: 'Smart Light Bulb',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Wi-Fi enabled smart LED bulb.',
            price: 14.99,
            stock: 200,
            categoryId: 11,
            supplierId: 6,
        },
        {
            id: 15,
            name: 'HDMI Cable 6ft',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'High-speed HDMI 2.1 cable.',
            price: 9.99,
            stock: 300,
            categoryId: 4,
            supplierId: 1,
        },
        {
            id: 16,
            name: 'External DVD Drive',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'USB 3.0 external DVD burner.',
            price: 39.5,
            stock: 70,
            categoryId: 7,
            supplierId: 3,
        },
        {
            id: 17,
            name: 'Fitness Tracker',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Waterproof fitness band with heart rate monitor.',
            price: 59.99,
            stock: 100,
            categoryId: 12,
            supplierId: 8,
        },
        {
            id: 18,
            name: 'Desktop Microphone',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'USB condenser microphone for streaming.',
            price: 74.99,
            stock: 50,
            categoryId: 8,
            supplierId: 4,
        },
        {
            id: 19,
            name: 'Smartwatch',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Smartwatch with GPS and call features.',
            price: 149.99,
            stock: 35,
            categoryId: 12,
            supplierId: 8,
        },
        {
            id: 20,
            name: 'Laptop Cooling Pad',
            imageUrl: 'https://res.cloudinary.com/dyc4xxmdw/image/upload/v1744778766/bamboo.png',
            description: 'Silent laptop cooler with adjustable height.',
            price: 22.0,
            stock: 65,
            categoryId: 5,
            supplierId: 6,
        },
    ];
};
